=== Boundle of Java Projects it includes.

* embededtomcat
* takeupmemory. Java Mainn application to takeup memory during certain tiempo. Used to do benchmarks
* hibernate. Simple hibernate stand alone project with no server and H2 embeded database. Used to
	test JPA. it has also a Groovy version to take adavatage of easeness of Groovy to create class
	 with no boilerplate 
* horasEE7faces. Simple Java web application done with netbenas wizards. It has JSF and primefaces.
	It requires a JEE server and data base and its data source. Tested in Glasfish Server
* horasSpringJaxrsJsp. Test of Jaxrs with Jersy along MVC viwth JSP view
* springsecuritybase. Sample of spring security basics
* hibernate PlayGround of some hibernate configurations. All can be runned with `gradle test --info`
** hibernate2groovy. Stand alone project with hiberante, groovy and h2 to play. Execute 
** hibernatelifecycle. Some test of hibernate to play with the lifecycle
** hibernatesqlite. Sqlite dialect.	
* openliberty. Small script to download and install liberty. Used to playground with several configs rapidly.
* openlibertycdi. based on the openliberty some samples of use of CDI, properties injection. login
* spring-boot-h2-persistence. Spring boot with h2 jpa. Some test about Transaccional
* spring-classic-cxf-ws. Classic Spring Framework CI 5 (no boot) with CXF 3.2 jax-ws
* simple web app. It is a maven simple web app with 1 servlet and 1 jsp to be deployed in web container.
* jsftomcat A simple jsf (Mojarra) to be runned in tomcat with 
the url will be `http://localhost:8080/SampleWebApp/mypath`
* camelsample two samples of apache camel. reanem the class from 2 to 1 to test and run with gradle run.
