drop table proyecto if exists
drop table tarea if exists
create table proyecto (id bigint generated by default as identity, codigo varchar(255), descripcion varchar(255), usuario varchar(255), primary key (id))
create table tarea (id bigint generated by default as identity, code varchar(255), descripcion varchar(255), horas integer not null, usuario varchar(255), primary key (id))
create table users( username varchar_ignorecase(50) not null primary key, password varchar_ignorecase(50) not null, enabled boolean not null)
create table authorities (username varchar_ignorecase(50) not null,authority varchar_ignorecase(50) not null,constraint fk_authorities_users foreign key(username) references users(username))
create unique index ix_auth_username on authorities (username,authority)

