/**
 * This file was generated by the Jeddict
 */
package org.jordi.horas.domain;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.ws.rs.FormParam;

/**
 * @author jordi
 */
@Entity
public class Projecto {

    @Column(unique = true, length = 12)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @FormParam("codigo")
    private String codigo;

    @Basic
    @FormParam("descripcion")
    private String descripcion;

    @Basic
    @FormParam("activo")
    private boolean activo = true;

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public boolean isActivo() {
        return this.activo;
    }

    public void setActivo(boolean activo) {
        this.activo = activo;
    }

}