/**
 * This file was generated by the Jeddict
 */
package org.jordi.horas.domain;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.ws.rs.FormParam;

/**
 * @author jordi
 */
@Entity
public class Tarea {

    @Column(length = 12)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @FormParam("codigo")
    private String codigo;

    @Basic
    @FormParam("descipcion")
    private String descipcion;

    public String getCodigo() {
        return this.codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public String getDescipcion() {
        return this.descipcion;
    }

    public void setDescipcion(String descipcion) {
        this.descipcion = descipcion;
    }

}